services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-service:latest
    ports:
      - "8080:8080"
    container_name: backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-service:latest
    ports:
      - "3000:80"
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
